package me.ndkshr.royaldeck

val ROYAL_DECK = mutableListOf(
    R.mipmap.card_10_of_clubs,
    R.mipmap.card_10_of_diamonds,
    R.mipmap.card_10_of_hearts,
    R.mipmap.card_10_of_spades,
    R.mipmap.card_2_of_clubs,
    R.mipmap.card_2_of_diamonds,
    R.mipmap.card_2_of_hearts,
    R.mipmap.card_2_of_spades,
    R.mipmap.card_3_of_clubs,
    R.mipmap.card_3_of_diamonds,
    R.mipmap.card_3_of_hearts,
    R.mipmap.card_3_of_spades,
    R.mipmap.card_4_of_clubs,
    R.mipmap.card_4_of_diamonds,
    R.mipmap.card_4_of_hearts,
    R.mipmap.card_4_of_spades,
    R.mipmap.card_5_of_clubs,
    R.mipmap.card_5_of_diamonds,
    R.mipmap.card_5_of_hearts,
    R.mipmap.card_5_of_spades,
    R.mipmap.card_6_of_clubs,
    R.mipmap.card_6_of_diamonds,
    R.mipmap.card_6_of_hearts,
    R.mipmap.card_6_of_spades,
    R.mipmap.card_7_of_clubs,
    R.mipmap.card_7_of_diamonds,
    R.mipmap.card_7_of_hearts,
    R.mipmap.card_7_of_spades,
    R.mipmap.card_8_of_clubs,
    R.mipmap.card_8_of_diamonds,
    R.mipmap.card_8_of_hearts,
    R.mipmap.card_8_of_spades,
    R.mipmap.card_9_of_clubs,
    R.mipmap.card_9_of_diamonds,
    R.mipmap.card_9_of_hearts,
    R.mipmap.card_9_of_spades,
    R.mipmap.card_ace_of_clubs,
    R.mipmap.card_ace_of_diamonds,
    R.mipmap.card_ace_of_hearts,
    R.mipmap.card_ace_of_spades,
    R.mipmap.card_jack_of_clubs,
    R.mipmap.card_jack_of_diamonds,
    R.mipmap.card_jack_of_hearts,
    R.mipmap.card_jack_of_spades,
    R.mipmap.card_king_of_clubs,
    R.mipmap.card_king_of_diamonds,
    R.mipmap.card_king_of_hearts,
    R.mipmap.card_king_of_spades,
    R.mipmap.card_queen_of_clubs,
    R.mipmap.card_queen_of_diamonds,
    R.mipmap.card_queen_of_hearts,
    R.mipmap.card_queen_of_spades,
)

val CARD_BACK = R.mipmap.card_back